Skip to content
fOrTnItEkIdDiE
EternityKernel
Repository navigation
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Build Kernel
Update main.yml #45
All jobs
Run details
build
failed now in 45s
Search logs
1s
21s
14s
Preparing to unpack .../device-tree-compiler_1.6.1-1_amd64.deb ...
Unpacking device-tree-compiler (1.6.1-1) ...
Setting up binutils-aarch64-linux-gnu (2.38-4ubuntu2.12) ...
Setting up libfdt1:amd64 (1.6.1-1) ...
Setting up libelf-dev:amd64 (0.186-1ubuntu0.1) ...
Setting up device-tree-compiler (1.6.1-1) ...
Processing triggers for man-db (2.10.2-1) ...
Not building database; man-db/auto-update is not 'true'.
Processing triggers for libc-bin (2.35-0ubuntu3.12) ...
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
No VM guests are running outdated hypervisor (qemu) binaries on this host.
6s
Run # GCC 64-bit
Cloning into 'gcc64'...
Cloning into 'gcc32'...
Cloning into 'clang'...
fatal: could not read Username for 'https://github.com': No such device or address
Error: Process completed with exit code 128.
0s
0s
0s
Post job cleanup.
/usr/bin/git version
git version 2.53.0
Temporarily overriding HOME='/home/runner/work/_temp/22f00fce-6614-4bf4-bbdb-30c6e1b47da6' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/EternityKernel/EternityKernel
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
/usr/bin/git config --local --name-only --get-regexp ^includeIf\.gitdir:
/usr/bin/git submodule foreach --recursive git config --local --show-origin --name-only --get-regexp remote.origin.url
0s
